app:
  name: hello-world

replicaCount: 4

image:
  repository: sample-node-app
  tag: v1

containerPort: 8000

service:
  port: 8000

ingress:
  host: hello-world-canary.learn.smartsenselabs.com
  tls:
    secretName: letsencrypt-prod-hello-world-tls

