apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: {{ .Values.containerPort }}
  strategy:
    canary:
      canaryService: {{ .Values.app.name }}-canary
      stableService: {{ .Values.app.name }}-stable
      trafficRouting:
        nginx:
          stableIngress: {{ .Values.app.name }}-ing-stable
      steps:
        - setWeight: 20
        - pause: { duration: 60s }
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
