# Stable service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-stable
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}

---
# Canary service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-canary
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
