apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-rollout
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:smartSenseSolutions/progressive-delivery-with-gitops.git
    path: helm-charts/canary-rollouts
    targetRevision: main
    helm:
      releaseName: canary-rollout
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
