app:
  name: hello-world

replicaCount: 4

image:
  repository: sample-node-app
  tag: v1

containerPort: 8080

service:
  port: 8080

ingress:
  host: hello-world-bg.learn.smartsenselabs.com
  tls:
    secretName: letsencrypt-prod-hello-world-tls

