providerRBAC:
  enabled: false

dashboard:
  enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    ingressClassName: "nginx"
    hosts:
      - argo-rollouts.learn.smartsenselabs.com
    paths:
      - /
    pathType: "Prefix"
    tls:
      - secretName: letsencrypt-prod-argo-rollouts-tls
        hosts:
          - argo-rollouts.learn.smartsenselabs.com

notifications:
  configmap:
    create: false